server:
  error:
    include-message: always
    include-stacktrace: on_param
    include-binding-errors: always
  port: 8081
jwt:
  public: 2413fb3709b05939f04cf2e92f7d0897fc2596f9ad0b8a9ea855c7bfebaae892
  private: 1dfg3b2tn7926359n8y2g9ng28q7w6q48245754n8qw7945vw6h9b4w57v6b9w47
  lifetime: 180m
spring:
  application:
    name: diplom
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/diplom
    username: diplom
    password: diplom
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 50
      data-source-properties:
        currentSchema: diplom
      auto-commit: false
  flyway:
    enabled: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-core.xml
  sql:
    init:
      mode: always